### ISSUE TITLE
does the load expression reuse the loader cache?

### ISSUE THREAD

**Issue by faassen** [malthe/chameleon#190]
I am not sure this is an issue -- I'm just trying to understand the code. Here goes:

The load expression uses `__loader`, which is initialized as `_loader` in the init of PageTemplateFile. This is always created as an instance of the loader_class.

The loader in `chameleon.loader` keeps a cache of templates in `self.registry` through a decorator.

If I create a page template loader and load a page template file, and then load it again, it'll come from the cache. But that page template file creates its _own_ loader again, so that when the load expression fires it will set it up in a _new_ cache. This means that if page template a loads up m, and page template b then loads up m again, b won't benefit from the cache of a -- it'll load m again.

I run into all this because I'm trying to create a custom loader, which I'd like to propagate into the templates it loads, so that any load expression in that template _also_ uses that loader. But custom loaders don't propagate to load expressions, do they? Instead I have to initialize it with its own class as a keyword argument, I think.

Again, I may get this all wrong -- I'm trying to read the code and I may be misunderstanding something. But I thought it was worth reporting.

**Comment by malthe** [comment]
There are two different kinds of loaders in Chameleon:

1. The first and most important loader is defined as ``BaseTemplate.loader`` and uses global state. It simply loads template code into a module which is injected into ``sys.modules`` and never freed.

2. The second loader is the one that implements the ``load: <path>`` expression. It's only responsible for translating an expression value to a path.

The second loader is instantiated per template because its behavior is relative to the location of that template.

**Comment by faassen** [comment]
Ahah! This I hope will help me get less confused about things and get my own code right.

So how does the loader class from 2 get propagated?

**Comment by malthe** [comment]
The built-ins should be inserted into the template variable scope. When you use a macro then the caller passes this scope to the callee. In this way ``__loader`` should be passed into the scope when evaluating a macro.

**Comment by faassen** [comment]
For context, the goal I have is as follows:

Instead of just loading the filename (say, master) directly, the system should first call a function with the filename as an argument, then get the real filename back and load that.

This is complicated by the fact that this function call should take into account state that is only known very late (like the request). So I'm trying to configure the loader just in time. I tried passing in __loader to variables but this doesn't appear to work.

**Comment by malthe** [comment]
The easiest way to accomplish this is probably a ``TemplateLoader`` implementation that knows about a global "request" variable (e.g. thread-local or other "clever" shim).

**Comment by faassen** [comment]
I don't use global request variables anywhere at all in Morepath, however, and I don't plan to, either.

**Comment by faassen** [comment]
I think all I really want is a load expression that uses __loader indirectly and has access to variables passed into render. Is that possible?

**Comment by faassen** [comment]
Hm, I guess I can make my *own* new expression type that takes an argument somehow.

**Comment by faassen** [comment]
Anyway, I give up on getting the loader to take rendering state into account. The only way to get the loader to respect rendering state is to use a thread local, as you suggest.

Ugly. Jinja2 doesn't appear to be any different.

**Comment by malthe** [comment]
You can definitely make your own expression – but the ``ProxyExpr`` is too simple to base it on because it simply takes a built-in name. You could use an expression that passes the template instance to the loader and then you could *bind* your request to e.g. ``BoundPageTemplateFile`` which then had the request object attached to it.

Alternatively, we could fix this in Chameleon such that the template loader always received the ``template`` object as an argument to ``load`` – instead of the current ``cls`` argument.

**Comment by malthe** [comment]
Closing this issue since there doesn't seem to be much traction on this feature!
