### ISSUE TITLE
Please document exceptions that render() may raise

### ISSUE THREAD

**Issue by PyDeq** [malthe/chameleon#194]
Please mention in the documentation the exceptions that can be raised during page template rendering.

**Comment by malthe** [comment]
None really. But in the cooking process (parsing and compiling) a number of exceptions can be raised and since this may be triggered during rendering (due to lazy compiling), you might want to catch any ``chameleon.exc.TemplateError`` exception and handle that specifically.

Alternatively, if you enable eager loading – via the ``CHAMELEON_EAGER=1`` environment setting – then all templates will be parsed and compiled on initialization through the ``cook_check()`` method.

**Comment by PyDeq** [comment]
Well, using different incorrect templates, I was able to raise ```OSError```, ```NameError```, ```TypeError``` and ```ValueError```. So, basically any Python exception can be raised when I call ```render()``` if the exception is raised in the given template. Could this fact be documented in the documentation?
And also the ```TemplateError``` is not mentioned anywhere in the documentation. Could you add it somewhere please?
(But effectively the user still cannot distinguish whether there was something wrong with the template that caused the ```TemplateError``` or whether an expression in the template raised the exception.)

**Comment by malthe** [comment]
@PyDeq does this changeset work for you?

**Comment by PyDeq** [comment]
Yes, perfect, thank you!

**Comment by malthe** [comment]
The result can be seen here http://chameleon.readthedocs.org/en/2.22/library.html#exceptions.
