### ISSUE TITLE
Temporary files are not deleted

### ISSUE THREAD

**Issue by nesaro** [malthe/chameleon#209]
One of our servers is generating thousands of temporary folders and files. After inspecting the code, it seems that ModuleLoader is not removing the files after reading them.

``` python
    def _load(self, base, filename):
        imp.acquire_lock()
        try:
            module = sys.modules.get(base)
            if module is None:
                f = open(filename, 'rb')
                try:
                    assert base not in sys.modules
                    module = imp.load_source(base, filename, f)
                finally:
                    f.close()
                    os.remove(filename)  #XXX This would remove the temporary file
        finally:
            imp.release_lock()

        return module.__dict__
```

Is this a good fix? Thanks

**Comment by malthe** [comment]
The temporary files – e.g. ``filename`` – are all created under the same temporary directory. Normally, this directory should be automatically deleted when the process ends:
```python
class ModuleLoader(object):
    def __init__(self, path, remove=False):
        self.path = path
        self.remove = remove

    def __del__(self, shutil=shutil):
        if not self.remove:
            return
        try:
            shutil.rmtree(self.path)
        except:
            warnings.warn("Could not clean up temporary file path: %s" % (self.path,))
```
If this does not happen, perhaps it's because the process is killed and is not allowed to exit?

If you run the process through ``systemd`` then the process should already have its own "temporary directory root" to start with. I would think that ``systemd`` has a means of making sure that a process' temporary directory is cleaned up after it ends even if the process itself is unable to (because it does not exit cleanly.)

But it could also be a compatibility issue with your version of Python – such that the above-mentioned ``__del__()`` is never called.

**Comment by nesaro** [comment]
Thank you @malthe,

I'm running pyramid/uwsgi/supervisor/nginx and python2.7.6 , but I could reproduce the problem in the test environment. 

As you pointed out, __del__ is not being called when the process is stopped. In the server the process receives a HUP signal; in the test environment it receives KeyboardInterrupt. 

In the [python documentation](https://docs.python.org/2/reference/datamodel.html#object.__del__) it says the following

     It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.

I think that the reason __del__ is not being called is either that it is not deleted at all or it is in a reference loop and it can't be collected. A context manager or an explicit call in a finally block would be guaranteed.

**Comment by malthe** [comment]
I'm pretty sure it was once using [atexit](https://docs.python.org/2/library/atexit.html) – but someone complained that this event wasn't really suitable either.

If this is a test-case, can't you create and tear down this loader in your test class' [tearDownClass](https://docs.python.org/2/library/unittest.html#unittest.TestCase.tearDownClass) method?

**Comment by nesaro** [comment]
Unfortunately this code is running in a production environment. atexit would require a global variable to store the current object which doesn't seem the best option. 

For the time being we will automate the temporary file deletion in the server, so we don't run out of space every few months

**Comment by malthe** [comment]
I am not sure what to do about this. Please re-open with a suggestion!
