### ISSUE TITLE
Outdated bit of documentation regarding structure keyword?

### ISSUE THREAD

**Issue by tiberiuichim** [malthe/chameleon#242]
According to section "Language extensions": https://chameleon.readthedocs.io/en/latest/reference.html#language-extensions

> The structure expression wraps an expression result as structure

and it is given as example:
```
<div>${structure: body.text}</div>
```

But then, just a bit bellow, there's this fragment:

> This is particularly useful for content which is substituted using the expression operator: "${...}" since the structure keyword is not allowed here.

which claims otherwise.

**Comment by malthe** [comment]
What this is supposed to mean is that the `structure` keyword (without colon) is understood only by `tal:content` and `tal:replace`.

In Chameleon we added `${...}` expressions and needed something similar to `structure`. So that became `structure: ...` – with a colon.

Chameleon's `structure:` is an expression type just like `load:` is. That said, the documentation could be a lot more clear on this.
