### ISSUE TITLE
Are ninja powers required to build a custom expression?

### ISSUE THREAD

**Issue by faxioman** [malthe/chameleon#278]
Hi.
I'm trying to build a simple expression like this:

```
<div tal:repeat="price prices">
   <div tal:content="money_localize: price"></div>
</div>
```
where "money_localize" returns the value expressed by the price variable in this form: "12.10 $".
Well, I can't figure out how to build this simple money_localize expression.
The integration documentation (https://chameleon.readthedocs.io/en/latest/library.html#extension) seems not useful in this context... and, of course, I'm not a ninja :)
Thanks!

**Comment by malthe** [comment]
This is an example which was developed some time ago, but should still work the same:

https://github.com/Pylons/pyramid_skins/blob/2463476db534fe6ca735e25c3cd1359b0782b3f7/src/pyramid_skins/models.py#L147

Basically, there is a class dict which maps the expression types available for a given template:
```python
class PageTemplate(BaseTemplate):
    expression_types = {
        'python': PythonExpr,
        'string': StringExpr,
        'not': NotExpr,
        'exists': ExistsExpr,
        'import': ImportExpr,
        'structure': StructureExpr,
        }

    [...]
```
We can extend that pretty easily using the `ProxyExpr` which simply calls a function with the string argument.

But that won't help you because you're trying to compute something from a local variable. But then – why not just use a function, i.e. `money_localize(price)`. You can even import that symbol using `import: <path>` (see `expression_types` above).

But if you really did want to implement this as an expression type, you'd have to subclass `PythonExpr`. Very similar to the example above.

**Comment by faxioman** [comment]
Great, I'll try subclassing PythonExpr. I have some other (more complex) expression and my templates are edited by designers ... so I prefer to not pass them python functions ;)
I think this answer could be added to the official doc!
Thank you!
